name: .NET Core
on:
  push:
    branches: [ features/init-commit ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore "./ChangeDetection.sln"

    - name: Build code
      run: dotnet build "./ChangeDetection.sln" --configuration Release --no- restore

    - name: Publish application
      run: dotnet publish "./src/ConsoleApp/ConsoleApp.csproj" -c Release -o myApp

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: "./ChangeDetection.sln" 