name: .NET Core
on:
  push:
    branches: [ features/init-commit ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore "./ChangeDetection.sln"

    - name: Build code
      run: dotnet build "./ChangeDetection.sln" --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish "./src/ConsoleApp/ConsoleApp.csproj" -c Release -o App

    - name: Publish application Self Contained
      run: dotnet publish "./src/ConsoleApp/ConsoleApp.csproj" -c Release --self-contained -r win-x86 -o AppSelf

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: ConsoleApp
       path: "./src/ConsoleApp/App" 

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: ConsoleAppSelf
       path: "./src/ConsoleApp/AppSelf" 